### ISSUE TITLE
Cannot delete DSCI object when DSC object still exists in upgrade tests

### ISSUE THREAD

**Issue by jiridanek** [skodjob/odh-e2e#164]
This is a flaky fail in upgrade tests. Operator added this finalizer thing and it's sometimes failing the test.

I believe we need to DELETE dsci with a retry now.

```
2024-10-17T16:51:19 ERROR [KubeResourceManager:423] Deleting DSCInitialization/default-dsci
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://api.crc.testing:6443/apis/dscinitialization.opendatahub.io/v1/dscinitializations/default-dsci. Message: admission webhook "operator.opendatahub.io" denied the request: Cannot delete DSCI object when DSC object still exists
. Received status: Status(apiVersion=v1, code=403, details=null, kind=Status, message=admission webhook "operator.opendatahub.io" denied the request: Cannot delete DSCI object when DSC object still exists
, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleDelete(OperationSupport.java:320)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.deleteAll(BaseOperation.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.delete(BaseOperation.java:500)
	at io.odh.test.framework.manager.resources.DataScienceInitializationType.delete(DataScienceInitializationType.java:52)
	at io.odh.test.framework.manager.resources.DataScienceInitializationType.delete(DataScienceInitializationType.java:20)
	at io.skodjob.testframe.resources.KubeResourceManager.deleteResource(KubeResourceManager.java:415)
	at io.skodjob.testframe.resources.KubeResourceManager.lambda$pushToStack$2(KubeResourceManager.java:216)
	at io.skodjob.testframe.resources.KubeResourceManager.lambda$deleteResources$15(KubeResourceManager.java:518)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://api.crc.testing:6443/apis/dscinitialization.opendatahub.io/v1/dscinitializations/default-dsci. Message: admission webhook "operator.opendatahub.io" denied the request: Cannot delete DSCI object when DSC object still exists
. Received status: Status(apiVersion=v1, code=403, details=null, kind=Status, message=admission webhook "operator.opendatahub.io" denied the request: Cannot delete DSCI object when DSC object still exists
, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:640)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:589)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:142)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-10-17T16:51:19 INFO  [Wait:66] Waiting for: Resource condition: deletion to be fulfilled for resource Namespace/redhat-ods-operator
2024-10-17T16:51:19 INFO  [OlmInstall:134] Deleting CSV rhods-operator.2.14.0
```

**Comment by jiridanek** [comment]
Yeah, upgrade passed twice in a row, seems to work.
